In [2]:
from validator.InstanceCO22 import InstanceCO22
from util import *
import pandas as pd

In [7]:
res = []
for i in range(1,31):
    inst  = loadInstance(i)
    res.append({
        'TRUCK_DISTANCE_COST': inst.TruckDistanceCost,
        'TRUCK_DAY_COST': inst.TruckDayCost,
        'TRUCK_COST':inst.TruckCost,
        'VAN_DISTANCE_COST':inst.VanDistanceCost,
        'VAN_DAY_COST':inst.VanDayCost,
        'VAN_COST':inst.VanCost,
        'DELIVER_EARLY_PENALTY':inst.deliverEarlyPenalty
        })
df = pd.DataFrame(res, index= list(range(1,31)))

In [8]:
df

,TRUCK_DISTANCE_COST,TRUCK_DAY_COST,TRUCK_COST,VAN_DISTANCE_COST,VAN_DAY_COST,VAN_COST,DELIVER_EARLY_PENALTY
1,20,200,0,10,100,0,0
2,20,200,0,10,100,0,0
3,20,200,0,10,100,0,0
4,20,200,0,10,100,0,0
5,20,200,0,10,100,0,0
6,20,200,100000,10,100,100000,0
7,20,200,0,1,10,0,0
8,20,200,0,10,100,0,0
9,20,200,0,10,100,0,0
10,20,2000,0,10,1000,0,0
11,20,200,0,10,100,0,5
12,20,200,0,10,100,0,5
13,20,200,0,10,100,0,5
14,20,200,0,10,100,0,5
15,20,200,0,10,100,0,5
16,20,200,100000,10,100,100000,5
17,20,200,0,1,10,0,5
18,20,200,0,10,100,0,5
19,20,200,0,10,100,0,5
20,20,2000,0,10,1000,0,5
21,20,2000,0,10,400,0,0
22,20,2000,0,10,400,0,0
23,20,2000,0,10,400,0,0
24,20,2000,0,10,400,0,0
25,20,2000,0,10,400,0,0
26,20,2000,0,10,400,5,5
27,20,2000,0,10,400,5,5
28,20,2000,0,10,400,5,5
29,20,2000,0,10,400,5,5
30,20,2000,0,10,400,5,5